Repository simple-icons/simple-icons-website-rs, pull requests merged in 2023-08, with the labels that each got.

#28 Fix position of copy icons
  Cargo.lock
  Cargo.toml
  components/src/grid/item/title.css
  components/src/grid/mod.css
  i18n/messages.pot
Labels: bug

#29 Fix params not removed from URL when values are empty
  components/src/url.rs
  i18n/messages.pot
Labels: bug

#31 Add more space between header copy icons and close button in modals
  components/src/grid/item/details.css
  components/src/modal.css
Labels: enhancement

#35 Only upload tests report on CI when failed
  .github/workflows/ci.yml
  Cargo.lock
  i18n/messages.pot
Labels: meta

#36 Load more icons on compact layout
  .github/workflows/ci.yml
  Makefile.toml
  app/src/pages.rs
  components/src/controls/layout.rs
  components/src/controls/search/mod.rs
  components/src/grid/icons_loader.rs
  components/src/grid/mod.rs
  config/src/lib.rs
  end2end/playwright.config.ts
  end2end/tests/helpers.ts
  i18n/messages.pot
Labels: enhancement

#37 Track modals state with URL
  USAGE.md
  app/src/app.rs
  components/src/controls/color_scheme.rs
  components/src/controls/download/mod.rs
  components/src/controls/layout.rs
  components/src/controls/order.rs
  components/src/controls/search/mod.rs
  components/src/footer/mod.rs
  components/src/grid/icons_loader.rs
  components/src/grid/item/deprecated.rs
  components/src/grid/item/details.rs
  components/src/grid/item/footer.rs
  components/src/grid/item/icon_preview.rs
  components/src/grid/item/links.rs
  components/src/grid/item/title.rs
  components/src/grid/mod.rs
  components/src/grid/scroll.rs
  components/src/header/mod.rs
  components/src/header/nav/language_selector.rs
  components/src/header/nav/mod.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/lib.rs
  components/src/modal.rs
  components/src/url.rs
  i18n/messages.pot
  i18n/src/lib.rs
Labels: enhancement

#38 Fix deprecated warnings style
  components/src/grid/item/deprecated.css
  components/src/grid/mod.css
  i18n/messages.pot
Labels: bug

#40 Fix custom license names in icon grid items
  components/src/controls/button.rs
  components/src/grid/item/links.css
  components/src/grid/item/links.rs
  components/src/header/nav/third_party_extensions.css
  components/src/modal.css
  i18n/messages.pot
Labels: bug

#44 Fix error ordering icons
  app/src/pages.rs
  app/stylesheet.css
  components/src/controls/order.rs
  components/src/controls/search/mod.rs
  components/src/copy.css
  components/src/copy.rs
  components/src/footer.css
  components/src/footer.rs
  components/src/footer/about.rs
  components/src/footer/mod.css
  components/src/lib.css
Labels: bug

#48 Add Discord Link and fix speech marks in translations.
  .github/workflows/auto-release.yml
  .github/workflows/ci.yml
  CONTRIBUTING.md
  components/src/header/nav/mod.rs
  end2end/tests/header/header.spec.ts
  i18n/locales/en-US/main.ftl
  i18n/locales/es-ES/main.ftl
  i18n/locales/fr-FR/main.ftl
  i18n/locales/it-IT/main.ftl
  i18n/locales/ja-JP/main.ftl
  i18n/locales/pt-PT/main.ftl
  i18n/locales/zh-CN/main.ftl
  i18n/locales/zh-HK/main.ftl
  i18n/locales/zh-TW/main.ftl
  scripts/fetch-deprecated-icons.ts
Labels: bug, enhancement

#60 Fix unicode normalization of slugs
  .github/workflows/ci.yml
  end2end/playwright.config.ts
  simple-icons/src/sdk/mod.rs
Labels: bug
