Repository simple-icons/simple-icons-website-rs, pull requests merged in 2023-11, with the labels that each got.

#112 Refactor localstorage and URL params code with macros
  .github/actions/get-toolchain/action.yml
  .github/workflows/auto-release.yml
  .github/workflows/verify.yml
  Cargo.lock
  Cargo.toml
  components/src/controls/color_scheme.rs
  components/src/controls/download/mod.rs
  components/src/controls/layout.rs
  components/src/controls/order.rs
  components/src/controls/search/mod.rs
  components/src/header/nav/language_selector.rs
  components/src/modal.rs
  components/src/storage.rs
  components/src/url.rs
  rust-toolchain.toml
Labels: refactor

#113 Replace svgpath JS library by Rust svg-path-cst
  Cargo.lock
  Cargo.toml
  Makefile.toml
  app/index.html
  components/Cargo.toml
  components/src/js_libs/svg-path-bbox.js
  components/src/js_libs/svg.rs
  components/src/js_libs/svg_bridge.js
  components/src/preview_generator/inputs.rs
  package-lock.json
  package.json
  simple-icons/Cargo.toml
  simple-icons/src/sdk/lint.rs
Labels: enhancement, dependencies

#117 Ukrainian translation
  i18n/languages.json
  i18n/locales/uk-UA/main.ftl
Labels: i18n

#121 Split path linting to show better error messages
  components/src/preview_generator/inputs.rs
  simple-icons/src/sdk/lint.rs
Labels: bug, preview generator

#123 Use fnm instead of nvm
  .husky/pre-commit
  CONTRIBUTING.md
  Makefile.toml
Labels: meta

#124 Fix non reactive SVG aria labels
  components/src/controls/search/mod.rs
  components/src/header/nav/button.rs
  components/src/preview_generator/inputs.rs
  components/src/svg.rs
Labels: bug

#129 Fix `get_simple_icons_3rd_party_extensions` macro
  macros/src/lib.rs
Labels: bug
