Repository simple-icons/simple-icons-website-rs, pull requests merged in 2023-10, with the labels that each got.

#64 Update Japanese translation
  i18n/locales/ja-JP/main.ftl
Labels: bug

#63 Add @sh-cho's Korean translation to this repo.
  i18n/locales/ko-KR/main.ftl
  i18n/src/lib.rs
Labels: enhancement

#68 Add Preview Generator
  .github/workflows/auto-release.yml
  .github/workflows/verify.yml
  .husky/pre-commit
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  Makefile.toml
  USAGE.md
  app/src/app.rs
  app/src/head.rs
  app/src/pages.rs
  app/stylesheet.css
  components/Cargo.toml
  components/src/button.css
  components/src/button.rs
  components/src/controls/search/mod.rs
  components/src/footer.rs
  components/src/grid/icons_loader.css
  components/src/grid/icons_loader.rs
  components/src/grid/mod.css
  components/src/grid/mod.rs
  components/src/header/nav/mod.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/header/title.rs
  components/src/lib.css
  components/src/lib.rs
  components/src/preview.css
  components/src/preview.rs
  i18n/locales/en-US/main.ftl
  i18n/locales/es-ES/main.ftl
  i18n/locales/fr-FR/main.ftl
  i18n/locales/it-IT/main.ftl
  i18n/locales/ja-JP/main.ftl
  i18n/locales/ko-KR/main.ftl
  i18n/locales/pt-PT/main.ftl
  i18n/locales/zh-CN/main.ftl
  i18n/locales/zh-HK/main.ftl
  i18n/locales/zh-TW/main.ftl
  macros/Cargo.toml
  macros/src/lib.rs
  package-lock.json
  package.json
  simple-icons/Cargo.toml
  simple-icons/src/color.rs
  simple-icons/src/lib.rs
  simple-icons/src/sdk/mod.rs
Labels: enhancement

#71 Fix preview generator not showing on Github Pages
  app/index.html
  app/preview.html
  app/src/pages.rs
  scripts/create-sitemap.ts
Labels: bug

#73 Set always badges labels as `simple-icons`
  components/src/preview.rs
Labels: design

#75 Match social badges with old implementation
  components/src/fetch.rs
  components/src/grid/item/details.rs
  components/src/grid/item/icon_preview.rs
  components/src/header/nav/button.rs
  components/src/preview.css
  components/src/preview.rs
Labels: design

#76 Add button to access icons grid from preview generator
  app/src/pages.rs
  components/src/button.rs
  components/src/lib.css
  components/src/lib.rs
  components/src/preview_generator.css
  components/src/preview_generator.rs
  i18n/locales/en-US/main.ftl
  i18n/locales/es-ES/main.ftl
  i18n/locales/fr-FR/main.ftl
  i18n/locales/it-IT/main.ftl
  i18n/locales/ja-JP/main.ftl
  i18n/locales/ko-KR/main.ftl
  i18n/locales/pt-PT/main.ftl
  i18n/locales/zh-CN/main.ftl
  i18n/locales/zh-HK/main.ftl
  i18n/locales/zh-TW/main.ftl
Labels: enhancement

#78 Add 404 error page
  app/404.html
  app/index.html
  app/src/app.rs
  app/src/pages.rs
  components/src/button.rs
  components/src/ids.rs
  components/src/svg_def.rs
  i18n/locales/en-US/main.ftl
  i18n/locales/es-ES/main.ftl
  i18n/locales/fr-FR/main.ftl
  i18n/locales/it-IT/main.ftl
  i18n/locales/ja-JP/main.ftl
  i18n/locales/ko-KR/main.ftl
  i18n/locales/pt-PT/main.ftl
  i18n/locales/zh-CN/main.ftl
  i18n/locales/zh-HK/main.ftl
  i18n/locales/zh-TW/main.ftl
Labels: enhancement

#79 Use a JSON file to define translation languages
  .gitignore
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  Makefile.toml
  app/index.html
  app/public/404.html
  app/public/assets/apple-touch-icon.png
  app/public/assets/check-white.svg
  app/public/assets/check.svg
  app/public/assets/copy-white.svg
  app/public/assets/copy.svg
  app/public/assets/dist/.keep
  app/public/assets/external-link-white.svg
  app/public/assets/external-link.svg
  app/public/assets/favicon.ico
  app/public/assets/favicon.png
  app/public/assets/legal-white.svg
  app/public/assets/legal.svg
  app/public/assets/logo.svg
  app/public/assets/og.png
  app/public/assets/opensearch.xml
  app/public/preview.html
  i18n/Cargo.toml
  i18n/build.rs
  i18n/languages.json
  i18n/src/lib.rs
  scripts/create-cname.ts
  scripts/create-sitemap.ts
Labels: i18n, refactor

#80 Serve preview generator under `preview/` path
  app/index.html
  app/public/preview/index.html
Labels: enhancement

#81 Add button for copying preview to preview generator
  components/src/button.css
  components/src/button.rs
  components/src/copy.js
  components/src/copy.rs
  components/src/ids.rs
  components/src/preview_generator.css
  components/src/preview_generator.rs
  components/src/svg_def.rs
  i18n/locales/en-US/main.ftl
  i18n/locales/es-ES/main.ftl
  i18n/locales/fr-FR/main.ftl
  i18n/locales/it-IT/main.ftl
  i18n/locales/ja-JP/main.ftl
  i18n/locales/ko-KR/main.ftl
  i18n/locales/pt-PT/main.ftl
  i18n/locales/zh-CN/main.ftl
  i18n/locales/zh-HK/main.ftl
  i18n/locales/zh-TW/main.ftl
Labels: enhancement

#82 Fix two styling errors
  components/src/button.css
  components/src/preview_generator.css
  i18n/locales/fr-FR/main.ftl
Labels: bug, design

#83 Add keyboard shortcuts to preview generator
  USAGE.md
  components/src/button.rs
  components/src/ids.rs
  components/src/preview_generator.rs
  components/src/svg_icon.rs
Labels: enhancement

#84 Update Twitter button to use X brand
  app/src/head.rs
  components/src/footer.css
  components/src/footer.rs
  i18n/locales/en-US/main.ftl
  i18n/locales/es-ES/main.ftl
  i18n/locales/fr-FR/main.ftl
  i18n/locales/it-IT/main.ftl
  i18n/locales/ja-JP/main.ftl
  i18n/locales/ko-KR/main.ftl
  i18n/locales/pt-PT/main.ftl
  i18n/locales/zh-HK/main.ftl
  i18n/locales/zh-TW/main.ftl
Labels: design

#86 Fix page padding style error
  app/src/pages.rs
  app/stylesheet.css
  components/src/controls/mod.css
  components/src/grid/mod.css
Labels: bug

#88 Split preview generator between multiple modules
  components/src/keyboard.rs
  components/src/lib.css
  components/src/lib.rs
  components/src/preview_generator.rs
  components/src/preview_generator/buttons.rs
  components/src/preview_generator/canvas.rs
  components/src/preview_generator/helpers.rs
  components/src/preview_generator/inputs.rs
  components/src/preview_generator/mod.css
  components/src/preview_generator/mod.rs
  components/src/svg_icon.rs
Labels: refactor

#89 Add linting for preview generator path input
  Makefile.toml
  app/index.html
  app/src/app.rs
  app/src/pages.rs
  components/src/button.rs
  components/src/controls/mod.rs
  components/src/footer.rs
  components/src/grid/item/footer.rs
  components/src/grid/scroll.rs
  components/src/header/nav/mod.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/js_libs/mod.rs
  components/src/js_libs/svg.js
  components/src/js_libs/svg.rs
  components/src/js_libs/svg_bridge.js
  components/src/lib.rs
  components/src/modal.rs
  components/src/preview_generator/buttons.rs
  components/src/preview_generator/inputs.rs
  components/src/preview_generator/mod.css
  components/src/preview_generator/mod.rs
  components/src/svg.rs
  components/src/svg_icon.rs
  package-lock.json
  package.json
  simple-icons/src/sdk/lint.rs
  simple-icons/src/sdk/mod.rs
Labels: enhancement

#93 Fix global URL parameters not passed to preview generator
  USAGE.md
  app/public/404.html
  app/public/preview.html
  app/public/preview/index.html
  components/src/header/nav/button.rs
  components/src/preview_generator/buttons.rs
  components/src/preview_generator/inputs.rs
Labels: bug

#94 Fix canvas badges alignment in preview generator
  components/src/preview_generator/canvas.rs
Labels: bug

#95 Add `collinear-segments` lint rule to path input of preview generator
  components/src/preview_generator/buttons.rs
  components/src/svg.rs
  simple-icons/src/sdk/lint.rs
Labels: enhancement

#96 Refactor and fix error
  app/src/app.rs
  components/src/controls/search/mod.rs
  components/src/copy.rs
  components/src/event.rs
  components/src/grid/mod.rs
  components/src/keyboard.rs
  components/src/lib.rs
  components/src/preview_generator/buttons.rs
  components/src/preview_generator/canvas.rs
  components/src/preview_generator/inputs.rs
  i18n/src/lib.rs
Labels: refactor

#102 Use localized icon aliases
  .husky/pre-commit
  Cargo.lock
  Cargo.toml
  Makefile.toml
  USAGE.md
  components/src/controls/search/mod.rs
  components/src/grid/item/deprecated.rs
  components/src/grid/item/details.rs
  components/src/grid/item/footer.rs
  components/src/grid/item/icon_preview.rs
  components/src/grid/item/mod.rs
  components/src/grid/item/title.rs
  i18n/src/lib.rs
  macros/src/lib.rs
  types/Cargo.toml
  types/src/lib.rs
Labels: enhancement

#103 Improvements for brand input of preview generator
  components/src/preview_generator/inputs.rs
  components/src/preview_generator/mod.css
Labels: enhancement

#104 Fix long brand names wrapping in preview generator
  components/src/preview_generator/mod.rs
Labels: bug

#105 Make preview generator accept `q` URL parameter
  USAGE.md
  app/public/preview.html
  app/public/preview/index.html
  app/src/app.rs
  app/src/pages.rs
  components/src/controls/search/mod.rs
  components/src/preview_generator/inputs.rs
  components/src/preview_generator/mod.rs
  components/src/url.rs
Labels: enhancement

#106 Show 'Go to header' button when scrolling
  components/src/grid/scroll.rs
Labels: enhancement

#107 Refactor with Leptos built-in components
  app/src/pages.rs
  components/src/button.rs
  components/src/controls/mod.rs
  components/src/controls/search/mod.rs
  components/src/footer.rs
  components/src/grid/icons_loader.rs
  components/src/grid/mod.rs
  components/src/grid/scroll.css
  components/src/grid/scroll.rs
  components/src/header/mod.rs
  components/src/header/nav/language_selector.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/header/title.rs
  components/src/ids.rs
  components/src/preview_generator/buttons.rs
  components/src/preview_generator/inputs.rs
  components/src/spinners.rs
  components/src/svg.rs
  end2end/tests/header/language-selector.spec.ts
  end2end/tests/helpers.ts
Labels: refactor, performance

#109 Refactor with leptos-use
  Cargo.lock
  Cargo.toml
  app/Cargo.toml
  app/src/app.rs
  app/src/main.rs
  components/Cargo.toml
  components/src/controls/color_scheme.rs
  components/src/controls/download/mod.rs
  components/src/controls/layout.rs
  components/src/controls/mod.rs
  components/src/controls/order.rs
  components/src/controls/search/mod.rs
  components/src/copy.rs
  components/src/grid/icons_loader.rs
  components/src/grid/item/details.rs
  components/src/grid/item/footer.rs
  components/src/grid/item/mod.rs
  components/src/grid/mod.rs
  components/src/grid/scroll.rs
  components/src/header/nav/button.rs
  components/src/header/nav/language_selector.rs
  components/src/header/nav/mod.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/keyboard.rs
  components/src/preview_generator/buttons.rs
  components/src/preview_generator/canvas.rs
  components/src/preview_generator/inputs.rs
  i18n/src/lib.rs
Labels: refactor, performance

#110 Improve icons details buttons
  components/src/controls/download/mod.rs
  components/src/grid/item/details.rs
Labels: enhancement

#111 Refactor components
  components/src/button.rs
  components/src/controls/button.css
  components/src/controls/button.rs
  components/src/controls/color_scheme.rs
  components/src/controls/layout.rs
  components/src/controls/mod.rs
  components/src/grid/item/details.rs
  components/src/grid/item/footer.rs
  components/src/grid/scroll.rs
  components/src/header/nav/button.css
  components/src/header/nav/button.rs
  components/src/header/nav/language_selector.rs
  components/src/header/nav/mod.css
  components/src/header/nav/mod.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/keyboard.rs
  components/src/modal.rs
  components/src/svg.rs
  i18n/build.rs
Labels: refactor
