Repository simple-icons/simple-icons-website-rs, pull requests merged in 2025-06, with the labels that each got.

#369 Simplify i18n configuration
  Cargo.lock
  Cargo.toml
  app/i18n/Cargo.toml
  app/i18n/src/lib.rs
Labels: dependencies

#372 Update leptos-fluent to v0.2.14
  .github/workflows/verify.yml
  Cargo.lock
  app/i18n/src/lib.rs
  components/grid/src/item/footer.rs
  components/grid/src/item/mod.rs
  components/header/src/nav/language_selector.rs
Labels: dependencies

#375 Fix Rust formatting configuration inconsistencies
  .github/workflows/verify.yml
  .vscode/settings.json
  CONTRIBUTING.md
  Makefile.toml
  app/src/pages.rs
  components/controls/src/order.rs
  components/grid/src/item/footer.rs
  components/header/src/nav/language_selector.rs
  components/menu/src/lib.rs
Labels: meta

#373 Remove jsdelivr, and unpkg header menu links
  app/i18n/locales/de-CH/main.ftl
  app/i18n/locales/en-US/main.ftl
  app/i18n/locales/es-ES/main.ftl
  app/i18n/locales/fr-FR/main.ftl
  app/i18n/locales/it-IT/main.ftl
  app/i18n/locales/ja-JP/main.ftl
  app/i18n/locales/ko-KR/main.ftl
  app/i18n/locales/pt-PT/main.ftl
  app/i18n/locales/ru-RU/main.ftl
  app/i18n/locales/uk-UA/main.ftl
  app/i18n/locales/zh-CN/main.ftl
  app/i18n/locales/zh-HK/main.ftl
  app/i18n/locales/zh-TW/main.ftl
  components/header/src/nav/mod.rs
Labels: design

#377 Upgrade XO to v1
  package-lock.json
  package.json
  xo.config.ts
Labels: dependencies

#381 Add Rust Apps Lints library
  Cargo.toml
  components/grid/src/item/details.rs
  components/preview-generator/src/buttons.rs
  components/preview-generator/src/canvas.rs
Labels: meta
