Repository simple-icons/simple-icons-website-rs, pull requests merged in 2025-02, with the labels that each got.

#280 Fix init from no order mode in localstorage when searching
  components/src/controls/order.rs
Labels: bug

#282 Split Simple Icons related crates into more crates
  Cargo.lock
  Cargo.toml
  Makefile.toml
  app/Cargo.toml
  app/src/head.rs
  components/Cargo.toml
  components/preview-generator/Cargo.toml
  components/preview-generator/src/buttons.rs
  components/preview-generator/src/helpers.rs
  components/preview-generator/src/inputs.rs
  components/preview-generator/src/lib.rs
  components/src/controls/download/pdf.rs
  components/src/grid/mod.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/header/title.rs
  libs/simple-icons-macros/Cargo.toml
  libs/simple-icons-macros/src/lib.rs
  libs/simple-icons-sdk/Cargo.toml
  libs/simple-icons-sdk/src/data.rs
  libs/simple-icons-sdk/src/lib.rs
  libs/simple-icons/Cargo.toml
  libs/simple-icons/src/color.rs
  libs/simple-icons/src/deprecated.rs
  libs/simple-icons/src/lib.rs
  libs/simple-icons/src/lint.rs
  libs/types/Cargo.toml
  libs/types/src/deprecation.rs
  libs/types/src/lib.rs
  libs/types/src/third_party_extension.rs
Labels: refactor

#283 Fix additional brand suggestions update on preview generator
  components/preview-generator/src/inputs.rs
  components/preview-generator/src/lib.css
Labels: bug, preview generator

#284 Drop `lazy_static` dependency
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile.toml
  app/public/assets/CNAME
  components/preview-generator/Cargo.toml
  components/preview-generator/src/lib.rs
  components/src/grid/mod.rs
  end2end/tests/header/language-selector.spec.ts
  libs/simple-icons-macros/src/lib.rs
  scripts/create-cname.ts
  scripts/create-sitemap.ts
Labels: dependencies

#285 Update contributing guide
  CONTRIBUTING.md
  USAGE.md
Labels: docs

#287 Use unchecked JS casting
  components/preview-generator/src/canvas.rs
  components/preview-generator/src/inputs.rs
  components/src/controls/download/mod.rs
  components/src/controls/download/pdf.rs
  components/src/controls/search/mod.rs
  components/src/copy.rs
  components/src/grid/item/details.rs
  components/src/grid/mod.rs
  libs/web-sys-simple-fetch/src/lib.rs
Labels: refactor

#291 Fix icons not loaded when scroll down and change to compact layout
  CONTRIBUTING.md
  Makefile.toml
  app/src/pages.rs
  components/src/controls/layout.rs
  components/src/grid/mod.rs
Labels: bug

#292 Don't render app index when redirecting
  Cargo.lock
  app/src/head.rs
  app/src/pages.rs
  components/Cargo.toml
  components/src/grid/ad.rs
  components/src/grid/item/mod.css
Labels: bug, performance

#293 Use badge-maker to build badges on preview generator
  .github/workflows/auto-release.yml
  .github/workflows/verify.yml
  .node-version
  Cargo.lock
  Cargo.toml
  Makefile.toml
  app/src/pages.rs
  components/preview-generator/Cargo.toml
  components/preview-generator/src/lib.rs
  components/src/controls/search/fuzzy.js
  components/src/controls/search/mod.rs
  libs/badge-maker/Cargo.toml
  libs/badge-maker/src/bindings.js
  libs/badge-maker/src/lib.js
  libs/badge-maker/src/lib.rs
  package-lock.json
  package.json
  scripts/comment-lines.ts
Labels: bug, preview generator

#294 Use simple-icons bot on CI
  .github/workflows/auto-release.yml
  .github/workflows/verify.yml
Labels: meta

#296 Add Mastodon and Facebook share buttons
  CONTRIBUTING.md
  Makefile.toml
  app/locales/en-US/main.ftl
  app/locales/es-ES/main.ftl
  app/locales/fr-FR/main.ftl
  app/locales/it-IT/main.ftl
  app/locales/ja-JP/main.ftl
  app/locales/ko-KR/main.ftl
  app/locales/pt-PT/main.ftl
  app/locales/ru-RU/main.ftl
  app/locales/uk-UA/main.ftl
  app/locales/zh-CN/main.ftl
  app/locales/zh-HK/main.ftl
  app/locales/zh-TW/main.ftl
  components/footer/src/lib.css
  components/footer/src/lib.rs
Labels: new feature

#297 Fix icon modal not opened using `modal=icon` in URL
  components/src/grid/mod.rs
Labels: bug

#298 Speed up first PDF generation
  components/src/controls/download/mod.rs
  components/src/controls/download/pdf.js
  components/src/controls/download/pdf.rs
  components/src/grid/item/details.rs
Labels: performance

#299 Fix bug in Automated Releases workflow
  .github/workflows/auto-release.yml
Labels: meta

#300 Separate components into different crates
  Cargo.lock
  Cargo.toml
  app/Cargo.toml
  app/src/app.rs
  app/stylesheet.css
  components/Cargo.toml
  components/copy/Cargo.toml
  components/copy/src/lib.css
  components/copy/src/lib.rs
  components/modal/Cargo.toml
  components/modal/src/lib.css
  components/modal/src/lib.rs
  components/search/Cargo.toml
  components/search/src/lib.rs
  components/src/button.css
  components/src/controls/search/mod.rs
  components/src/grid/item/details.rs
  components/src/grid/item/footer.rs
  components/src/grid/item/icon_preview.rs
  components/src/grid/item/title.rs
  components/src/grid/mod.rs
  components/src/header/nav/language_selector.rs
  components/src/header/nav/third_party_extensions.rs
  components/src/lib.css
  components/src/lib.rs
Labels: refactor

#302 Fix color scheme not working in 404 page on production
  app/src/app.rs
Labels: bug

#303 Fix errors in Automated Releases workflow
  .github/workflows/auto-release.yml
Labels: meta

#304 Add Bluesky share button
  Cargo.lock
  app/locales/en-US/main.ftl
  app/locales/es-ES/main.ftl
  app/locales/fr-FR/main.ftl
  app/locales/it-IT/main.ftl
  app/locales/ja-JP/main.ftl
  app/locales/ko-KR/main.ftl
  app/locales/pt-PT/main.ftl
  app/locales/ru-RU/main.ftl
  app/locales/uk-UA/main.ftl
  app/locales/zh-CN/main.ftl
  app/locales/zh-HK/main.ftl
  app/locales/zh-TW/main.ftl
  components/footer/Cargo.toml
  components/footer/src/lib.css
  components/footer/src/lib.rs
Labels: design, new feature

#306 Avoid crashing on production using router 404 fallback
  app/src/app.rs
  components/controls/src/color_scheme.rs
Labels: bug, refactor

#308 Fix "share on X" icon color on dark mode
  components/footer/src/lib.css
Labels: bug, design

#309 Create German (Switzerland) translation
  app/locales/de-CH/main.ftl
Labels: i18n

#310 Add alphabetic and color reverse sorting modes
  components/controls/order-types/src/lib.rs
  components/controls/src/order.rs
  end2end/tests/controls/order.spec.ts
  end2end/tests/controls/search.spec.ts
Labels: design, new feature

#314 Allow to init order mode from URL parameter
  USAGE.md
  components/controls/order-types/src/lib.rs
  components/controls/src/order.rs
  components/footer/src/lib.rs
  components/grid/types/src/lib.rs
  components/url/src/lib.rs
Labels: new feature

#318 Use `old` aliases to search
  libs/simple-icons-macros/src/lib.rs
  libs/simple-icons-sdk/src/data.rs
  libs/types/src/lib.rs
Labels: enhancement

#319 Detect renamed icons building deprecations
  app/locales/de-CH/main.ftl
  app/locales/en-US/main.ftl
  app/locales/es-ES/main.ftl
  app/locales/fr-FR/main.ftl
  app/locales/it-IT/main.ftl
  app/locales/ja-JP/main.ftl
  app/locales/ko-KR/main.ftl
  app/locales/pt-PT/main.ftl
  app/locales/ru-RU/main.ftl
  app/locales/uk-UA/main.ftl
  app/locales/zh-CN/main.ftl
  app/locales/zh-HK/main.ftl
  app/locales/zh-TW/main.ftl
  components/grid/src/item/deprecated.rs
  components/grid/src/item/details.rs
  components/grid/src/item/mod.rs
  libs/simple-icons-macros/src/lib.rs
  libs/simple-icons/src/deprecated.rs
  libs/types/src/deprecation.rs
Labels: enhancement
